CREATE TABLE NOTICE (
    ID NUMBER,
    TITLE NVARCHAR2(100),
    WRITER_ID NVARCHAR2(50),
    CONTENT CLOB,
    REGDATE TIMESTAMP,
    HIT NUMBER,
    FILES NVARCHAR2(1000)
);

CREATE TABLE "COMMENT" (
    ID NUMBER,
    CONTENT NVARCHAR2(2000),
    REGDATE TIMESTAMP,
    WRITER_ID NVARCHAR2(50),
    NOTICE_ID NUMBER
);

CREATE TABLE ROLE (
    ID VARCHAR2(50),
    DISCRIPTION NVARCHAR2(500)
);

CREATE TABLE MEMBER_ROLE (
    MEMBER_ID NVARCHAR2(50),
    ROLE_ID VARCHAR2(50)
);


INSERT INTO NOTICE VALUES(1, 'jdbc란 무엇인가?', 'newlec', 'aaa', SYSDATE, 0, '');
COMMIT;


