CREATE TABLE NOTICE (
    ID NUMBER,
    TITLE NVARCHAR2(100),
    WRITER_ID NVARCHAR2(50),
    CONTENT CLOB,
    REGDATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    HIT NUMBER DEFAULT 0,
    FILES NVARCHAR2(1000)
);

DROP TABLE NOTICE;

CREATE TABLE "COMMENT" (
    ID NUMBER,
    CONTENT NVARCHAR2(2000),
    REGDATE TIMESTAMP,
    WRITER_ID NVARCHAR2(50),
    NOTICE_ID NUMBER
);

CREATE TABLE ROLE (
    ID VARCHAR2(50),
    DISCRIPTION NVARCHAR2(500)
);

CREATE TABLE MEMBER_ROLE (
    MEMBER_ID NVARCHAR2(50),
    ROLE_ID VARCHAR2(50)
);


INSERT INTO NOTICE VALUES(1, 'jdbc란 무엇인가?', 'newlec', 'aaa', SYSDATE, 0, '');
COMMIT;

-----------------------------------------------------------------------10/29
INSERT INTO NOTICE VALUES(2, 'jdbc란 무엇인가?', 'newlec', 'aaa', SYSDATE, 0, '');
INSERT INTO NOTICE VALUES(3, 'jdbc란 무엇인가?', 'newlec', 'aaa', SYSDATE, 0, '');
COMMIT;

select * from NOTICE;

-----------------------------------------------------------------------10/30
CREATE TABLE MEMBER (
    ID NVARCHAR2(50),
    PWD NVARCHAR2(50),
    NAME NVARCHAR2(50),
    GENDER NCHAR(2),
    BIRTHDAY CHAR(10),
    PHONE CHAR(13),
    REGDATE DATE,
    EMAIL VARCHAR2(200)
);

SELECT * FROM NOTICE ORDER BY ID DESC;

SELECT NOTICE_SEQ.NEXTVAL FROM DUAL;

INSERT INTO NOTICE (title, writer_id,content,files)
VALUES ('TEST', 'newlec', 'tset content', '');

SELECT * FROM NOTICE;

ROLLBACK;
COMMIT;

UPDATE NOTICE
SET
    TITLE ='테스트',
    CONTENT = '공부중',
    FILES = ''
WHERE ID=6;
ROLLBACK;

UPDATE NOTICE
SET
    ID=3
WHERE ID=9;

INSERT INTO NOTICE VALUES(8, 'jdbc란 무엇인가?', '뉴버지', 'aaa', SYSDATE, 0, '');
INSERT INTO NOTICE VALUES(9, 'jdbc공부', 'A', '뉴렉처최고', SYSDATE, 0, '');
INSERT INTO NOTICE VALUES(4, 'jdbc를', 'LAST', 'JDBC 얼른 끝내자', SYSDATE, 0, '');

SELECT * FROM NOTICE ORDER BY ID;


